### ISSUE TITLE
Great for developement but app.js is too big for production

### ISSUE THREAD

**Issue by Dhyey** [planetoftheweb/reactinterface#1]
Hi,
This is really a great project to get started with react browserify workflow. Even though it is great for development, app.js file here is too big (~3MB). How can we reduce that? This project would be much more use full if we probably can have builds/devApp and builds/prodApp as two separate builds

**Comment by planetoftheweb** [comment]
I agree, but this wasn't a course about workflows, so I kept it for development only.
