### ISSUE TITLE
cloaning process not successful

### ISSUE THREAD

**Issue by ayagirma** [planetoftheweb/reactinterface#4]
after branch, there is a colon (:) sign at the end of the folder 04 _02b.  then, unable to further after this not even type anything.

**Comment by jfambrini** [comment]
Yes the same happening with me, when I re-start the Terminal, it was not finding gulp so I did a local install of gulp. When I run gulp I get assert.js:350
    throw err;
    ^
AssertionError [ERR_ASSERTION]: Task function must be specified

**Comment by planetoftheweb** [comment]
This course needs an update, not just because of the gulp issue, but because of changes within the framework. It's on my schedule to re-do, but I don't have a due date to give you right now.
