### ISSUE TITLE
Grunt / Gulp Instructions

### ISSUE THREAD

**Issue by Alejandro-sin** [planetoftheweb/reactinterface#5]
Hello there,  hope you do great.
In the readme intructions file says  "run >grunt" but there are no dependencies such grunt or grunt-file.js, you are using gulp and gulpfile.js. 

And thanks for the content!

**Comment by planetoftheweb** [comment]
Thanks. Fixed it. There's a newer version of this course, which uses Hooks, Tailwind CSS and who knows what for the build tools. I think it's just npm start. ;)
